Add Cilium load balancer
metal-stack/metal-ccm pull request #94
Opened 2024-06-06 10:45 UTC by iljarotar

This PR adds a Cilium load balancer as an alternative to metalLB.

2024-06-19 06:38 UTC, robertvolkmann commented on metal/cloud.go
> +	}
For backwards compatibility, the default case should be metallb too.

2024-10-16 12:14 UTC, majst01 commented on pkg/controllers/loadbalancer/addresspool.go
>  	cidr := ip + "/32"
This is IPv4 only

2024-10-17 07:19 UTC, majst01 requested changes

2024-10-17 07:19 UTC, majst01 commented on pkg/controllers/loadbalancer/cilium/config.go
> +}
This is duplicate to metallb/config.go

2024-10-17 07:19 UTC, majst01 commented on pkg/controllers/loadbalancer/cilium/config.go
> +func (cfg *ciliumConfig) ToYAML() (string, error) {
Only used here, please unexport

2024-10-17 07:19 UTC, majst01 commented on pkg/controllers/loadbalancer/cilium/config.go
> +				Kind:       "CiliumBGPPeeringPolicy",
```suggestion
				Kind:       ciliumv2alpha1.BGPPKindDefinition,
```

2024-10-17 07:19 UTC, majst01 commented on pkg/controllers/loadbalancer/cilium/config.go
> +				Kind:       "CiliumLoadBalancerIpPool",
```suggestion
				Kind:       ciliumv2alpha1.PoolKindDefinition,
```

2024-10-17 07:32 UTC, robertvolkmann commented on pkg/controllers/loadbalancer/cilium/config.go
> +				APIVersion: "cilium.io/v2alpha1",
```suggestion
				APIVersion: ciliumv2alpha1.CustomResourceDefinitionGroup + "/" + CustomResourceDefinitionVersion,
```

2024-10-23 06:10 UTC, robertvolkmann requested changes

2024-10-23 06:10 UTC, robertvolkmann commented on pkg/controllers/housekeeping/housekeeper.go
> +					// node was not modified and ip address has not changed, not updating load balancer config
Inconsistent naming. In some places it is "loadbalancer" and in other places "load balancer".

2024-10-23 06:24 UTC, robertvolkmann approved these changes

2024-10-24 11:51 UTC, Gerrit91 approved these changes

2024-10-24 13:02 UTC, Gerrit91 approved these changes

2024-10-24 13:03 UTC, majst01 approved these changes

2024-10-24 13:03 UTC, merged